import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components';

const Container = styled.div`
  color: red;
`;

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Enabling SSR of Styled Components
      </h1>
    </Container>
  )
}

export default Home
